### ISSUE TITLE
Maven package problem

### ISSUE THREAD

**Issue by longnguyen2306** [dermatologist/fhirql#1]
Hi,

I cloned your project and try to build it with maven. Following error was encountered:

`Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.2:enforce (enforce-java) on project fhirql: Execution enforce-java of goal org.apache.maven.plugins:maven-enforcer-plugin:1.2:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:1.2:enforce: java.lang.ExceptionInInitializerError: null`

Do you have any idea?

**Comment by dermatologist** [comment]
Hi @longnguyen2306 : Are you using Java 8?

**Comment by longnguyen2306** [comment]
Hi yes, the problem was solved after I remove the parent package and add it as a normal package
